// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CommissionManagement.Models;

public partial class CommissionOrder
{
    public int Id { get; set; }

    public string OrderCode { get; set; }

    public int PeriodId { get; set; }

    public string Nickname { get; set; }

    public string Email { get; set; }

    public int? SocialId { get; set; }

    public string SocialUrl { get; set; }

    public int CommissionTypeId { get; set; }

    public string CommissionSetting { get; set; }

    public int PaymentStatus { get; set; }

    public int WorkStatus { get; set; }

    public int SelectionStatus { get; set; }

    public string AdminNote { get; set; }

    public DateOnly? ScheduledDate { get; set; }

    public DateOnly CreatedAt { get; set; }
}