// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CommissionManagement.Models;

public partial class CommissionType
{
    public int Id { get; set; }

    public string TypeName { get; set; }

    public bool IsActive { get; set; }

    public bool IsHomeVisible { get; set; }

    public int HomeSortOrder { get; set; }

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();
}