// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CommissionManagement.Models;

public partial class CommissionContext : DbContext
{
    public CommissionContext(DbContextOptions<CommissionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CommissionOrder> CommissionOrders { get; set; }

    public virtual DbSet<CommissionPeriod> CommissionPeriods { get; set; }

    public virtual DbSet<CommissionType> CommissionTypes { get; set; }

    public virtual DbSet<Config> Configs { get; set; }

    public virtual DbSet<Image> Images { get; set; }

    public virtual DbSet<QaQuestion> QaQuestions { get; set; }

    public virtual DbSet<QaSetting> QaSettings { get; set; }

    public virtual DbSet<SocialPlatform> SocialPlatforms { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CommissionOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__commissi__3213E83F9D619D97");

            entity.ToTable("commission_order");

            entity.HasIndex(e => new { e.PeriodId, e.Email }, "UQ_commission_order_period_email").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AdminNote)
                .HasMaxLength(200)
                .HasColumnName("admin_note");
            entity.Property(e => e.CommissionTypeId).HasColumnName("commission_type_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("email");
            entity.Property(e => e.Nickname)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("nickname");
            entity.Property(e => e.OrderCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("order_code");
            entity.Property(e => e.PaymentStatus)
                .HasDefaultValue(1)
                .HasColumnName("payment_status");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.ScheduledDate).HasColumnName("scheduled_date");
            entity.Property(e => e.SelectionStatus)
                .HasDefaultValue(1)
                .HasColumnName("selection_status");
            entity.Property(e => e.SocialId).HasColumnName("social_id");
            entity.Property(e => e.SocialUrl)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("social_url");
            entity.Property(e => e.WorkStatus)
                .HasDefaultValue(1)
                .HasColumnName("work_status");
        });

        modelBuilder.Entity<CommissionPeriod>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__commissi__3213E83F28A0301D");

            entity.ToTable("commission_period");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CloseAt).HasColumnName("close_at");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.MaxWinners).HasColumnName("max_winners");
            entity.Property(e => e.OpenAt).HasColumnName("open_at");
            entity.Property(e => e.Ststus)
                .HasDefaultValue((byte)1)
                .HasColumnName("ststus");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("title");
        });

        modelBuilder.Entity<CommissionType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__commissi__3213E83F7614CF76");

            entity.ToTable("commission_type");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.BasePrice).HasColumnName("basePrice");
            entity.Property(e => e.FullDescription).HasColumnName("fullDescription");
            entity.Property(e => e.HomeSortOrder).HasColumnName("home_sort_order");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.IsHomeVisible).HasColumnName("is_home_visible");
            entity.Property(e => e.ShortDescription).HasColumnName("shortDescription");
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("type_name");
        });

        modelBuilder.Entity<Config>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__config__3213E83F0D3ED332");

            entity.ToTable("config");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.NoticeContent).HasColumnName("noticeContent");
        });

        modelBuilder.Entity<Image>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__images__3213E83FEC3B7DA5");

            entity.ToTable("images");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CommissionTypeId).HasColumnName("commission_type_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.ImagePath)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("image_path");
            entity.Property(e => e.IsVisible)
                .HasDefaultValue(true)
                .HasColumnName("is_visible");
            entity.Property(e => e.SortOrder)
                .HasDefaultValue(1)
                .HasColumnName("sort_order");
            entity.Property(e => e.ThumbPath)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("thumb_path");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");
        });

        modelBuilder.Entity<QaQuestion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__qa_quest__3213E83FFCFBE7F8");

            entity.ToTable("qa_question");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("email");
            entity.Property(e => e.Question)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("question");
        });

        modelBuilder.Entity<QaSetting>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__qa_setti__3213E83FA5C896B1");

            entity.ToTable("qa_setting");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Answer)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("answer");
            entity.Property(e => e.IsVisible)
                .HasDefaultValue(true)
                .HasColumnName("is_visible");
            entity.Property(e => e.Question)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("question");
            entity.Property(e => e.SortOrder)
                .HasDefaultValue(1)
                .HasColumnName("sort_order");
        });

        modelBuilder.Entity<SocialPlatform>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__social_p__3213E83F87B8FB21");

            entity.ToTable("social_platform");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.SocialName)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("social_name");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC07C55002B8");

            entity.HasIndex(e => e.Username, "UQ__Users__536C85E449DD59CC").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Admin");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}