// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CommissionManagement.Models;

public partial class CommissionPeriod
{
    public int Id { get; set; }

    public string Title { get; set; }

    public DateOnly OpenAt { get; set; }

    public DateOnly CloseAt { get; set; }

    public byte Ststus { get; set; }

    public byte? MaxWinners { get; set; }

    public DateOnly CreatedAt { get; set; }
}