// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CommissionManagement.Models;

public partial class Image
{
    public int Id { get; set; }

    public int CommissionTypeId { get; set; }

    public string Title { get; set; }

    public string ImagePath { get; set; }

    public string ThumbPath { get; set; }

    public int SortOrder { get; set; }

    public bool IsVisible { get; set; }

    public DateOnly CreatedAt { get; set; }

    public DateOnly UpdatedAt { get; set; }
}