// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CommissionManagement.Models;

public partial class QaQuestion
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Question { get; set; }

    public DateOnly CreatedAt { get; set; }
}