// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CommissionManagement.Models;

public partial class QaSetting
{
    public int Id { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public int SortOrder { get; set; }

    public bool IsVisible { get; set; }
}