// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CommissionManagement.Models;

public partial class SocialPlatform
{
    public int Id { get; set; }

    public string SocialName { get; set; }

    public bool IsActive { get; set; } = true;
}